import Link from "next/link";
import { Card, FinalCta, PageHero, PageShell, SectionContainer } from "@/components/section";
import { createPageMetadata, services, site } from "@/lib/site";

export const metadata = createPageMetadata({ title: "RN Assessment & Care Plan Services", description: "Explore RN assessments and individualized care-plan services from Sosena Nursing Solutions for Washington care providers, referral teams, and families.", path: "/services" });

export default function ServicesPage() {
  return <PageShell><PageHero eyebrow="Professional nursing services" title="RN Assessments & Individualized Care Plans" intro={`Two focused clinical services provided by ${site.provider} for authorized providers, professionals, care teams, and families in Washington.`}><Link className="inline-flex min-h-12 items-center justify-center rounded-xl bg-navy px-5 py-3 text-sm font-extrabold text-white" href="/request-assessment">Request an Assessment</Link></PageHero><SectionContainer><div className="grid gap-6 lg:grid-cols-2">{services.map((service,index)=><Card className="p-6 sm:p-8" key={service.href}><p className="text-xs font-black uppercase tracking-[0.16em] text-teal">Service 0{index+1}</p><h2 className="mt-3 text-3xl font-black tracking-tight text-navy">{service.title}</h2><p className="mt-4 leading-7 text-slate">{service.description}</p><ul className="mt-5 grid gap-3 text-sm text-slate">{service.examples.map((item)=><li className="flex gap-3" key={item}><span aria-hidden="true" className="text-teal">●</span>{item}</li>)}</ul><Link className="mt-6 inline-flex min-h-11 items-center font-extrabold text-teal underline decoration-teal/30 underline-offset-4" href={service.href}>View service details</Link></Card>)}</div><div className="mt-10 rounded-[24px] bg-[#EDF6FA] p-6 sm:p-8"><h2 className="text-2xl font-black text-navy">Clear clinical scope</h2><p className="mt-3 max-w-4xl leading-7 text-slate">SNS provides the nursing assessment and care plan. SNS is not a placement agency and does not make an Adult Family Home’s admission decision. The receiving home reviews the documented needs and determines whether it can appropriately meet them.</p></div></SectionContainer><FinalCta /></PageShell>;
}
