import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Card, FinalCta, PageHero, PageShell, SectionContainer } from "@/components/section";
import { resourcePath, resources } from "@/lib/resources";
import { createPageMetadata } from "@/lib/site";
export const dynamicParams = false;
export function generateStaticParams(){return resources.map((resource)=>({slug:resource.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const resource=resources.find((item)=>item.slug===slug);return resource?createPageMetadata({title:resource.title,description:resource.description,path:resourcePath(resource)}):{};}
export default async function ResourcePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const resource=resources.find((item)=>item.slug===slug);if(!resource)notFound();return <PageShell><PageHero eyebrow="SNS Resource" title={resource.title} intro={resource.intro}/><SectionContainer innerClassName="max-w-5xl"><nav aria-label="Breadcrumb" className="mb-10 flex flex-wrap gap-2 text-sm text-slate"><Link className="underline underline-offset-4" href="/">Home</Link><span aria-hidden="true">/</span><Link className="underline underline-offset-4" href="/resources">Resources</Link><span aria-hidden="true">/</span><span aria-current="page">{resource.title}</span></nav><div className="grid gap-6">{resource.sections.map((section)=><Card className="sm:p-8" key={section.heading}><h2 className="text-2xl font-black text-navy">{section.heading}</h2>{section.paragraphs?.map((paragraph)=><p className="mt-4 leading-7 text-slate" key={paragraph}>{paragraph}</p>)}{section.bullets?<ul className="mt-5 grid gap-3 text-slate sm:grid-cols-2">{section.bullets.map((item)=><li className="flex gap-3" key={item}><span aria-hidden="true" className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-teal"/>{item}</li>)}</ul>:null}</Card>)}</div>{resource.relatedService?<Link className="mt-8 inline-flex min-h-12 items-center justify-center rounded-xl bg-navy px-5 py-3 text-sm font-extrabold text-white" href={`/services/${resource.relatedService}`}>View the related SNS service</Link>:null}</SectionContainer><FinalCta /></PageShell>}
