export type ResourceDefinition = { slug: string; title: string; description: string; intro: string; sections: readonly { heading: string; paragraphs?: readonly string[]; bullets?: readonly string[] }[]; relatedService?: string; };
export const resources: readonly ResourceDefinition[] = [
  { slug: "what-is-an-rn-assessment-for-an-adult-family-home", title: "What Is an RN Assessment for an Adult Family Home?", description: "Learn what an RN assessment documents for Adult Family Home placement and ongoing care planning.", intro: "An RN assessment is a structured clinical review of a person’s current health, function, cognition, behavior, medications, safety, and daily support needs.", sections: [
    { heading: "Why the assessment matters", paragraphs: ["The assessment gives authorized providers and care teams a clear clinical picture. A receiving Adult Family Home uses that information as part of its own review of whether it can appropriately meet the person’s needs."] },
    { heading: "What is commonly reviewed", bullets: ["Health history and diagnoses", "Medication support", "Cognition and communication", "Mobility and personal care", "Behavioral and safety needs", "Preferences and routines"] },
    { heading: "What happens next", paragraphs: ["Assessment findings can provide the clinical foundation for an individualized or negotiated care plan. SNS explains the appropriate next step based on the requested service."] },
  ], relatedService: "initial-rn-assessment" },
  { slug: "when-is-an-assessment-needed-before-afh-placement", title: "When Is an Assessment Needed Before AFH Placement?", description: "Understand common situations when an RN assessment may support an Adult Family Home placement decision.", intro: "An assessment is often requested when an adult is preparing for a new residential-care setting and current care needs must be clearly documented.", sections: [
    { heading: "Common transition points", bullets: ["Hospital discharge to an Adult Family Home", "Move from assisted living or another care setting", "Family preparing for AFH placement", "Referral professional coordinating a transition", "Receiving home reviewing prospective care needs"] },
    { heading: "The assessment does not make the placement decision", paragraphs: ["SNS documents assessed care needs. The receiving Adult Family Home determines whether it can appropriately meet those needs and whether admission is suitable."] },
    { heading: "Start with basic coordination information", paragraphs: ["A public request should include only contact, location, timing, and service information. SNS provides separate instructions when authorized clinical records are needed."] },
  ], relatedService: "initial-rn-assessment" },
  { slug: "what-is-a-negotiated-care-plan", title: "What Is a Negotiated Care Plan?", description: "Learn how an individualized negotiated care plan connects assessed needs with practical daily-care guidance.", intro: "A negotiated care plan is the written, person-centered plan used to organize how assessed needs, preferences, risks, and daily support will be addressed.", sections: [
    { heading: "Assessment first, plan second", paragraphs: ["A current assessment provides the clinical foundation. The care plan then translates relevant findings into understandable support instructions and care approaches."] },
    { heading: "What the plan can organize", bullets: ["Personal-care assistance", "Mobility and transfer support", "Medication support", "Safety precautions", "Preferences and routines", "Monitoring and communication expectations"] },
    { heading: "A practical document", paragraphs: ["The goal is clear direction for authorized providers and caregivers without losing the individual’s preferences and daily routines."] },
  ], relatedService: "negotiated-care-plan" },
  { slug: "initial-assessment-vs-annual-assessment-renewal", title: "Initial Assessment vs. Annual Assessment Renewal", description: "Compare an initial Adult Family Home RN assessment with an annual assessment renewal.", intro: "Both services document current care needs, but they begin from different points in the person’s care journey.", sections: [
    { heading: "Initial RN Assessment", paragraphs: ["An initial assessment establishes a comprehensive clinical picture for a new admission, placement, or transition. It documents current needs at the start of the care relationship."] },
    { heading: "Annual Assessment Renewal", paragraphs: ["An annual renewal revisits the current picture, reviews changes since the prior assessment, and identifies information that may require updated care planning."] },
    { heading: "Which service is appropriate?", paragraphs: ["The answer depends on the resident’s situation, existing documentation, timing, and the purpose of the review. SNS can clarify the service during basic coordination."] },
  ], relatedService: "annual-assessment-renewal" },
  { slug: "when-is-a-change-in-condition-assessment-needed", title: "When Is a Change in Condition Assessment Needed?", description: "Learn when a focused RN reassessment may be appropriate after a significant change in an AFH resident’s needs.", intro: "A change in condition assessment focuses on a meaningful new development that may affect health, function, safety, or the level of support required.", sections: [
    { heading: "Common reasons for reassessment", bullets: ["Hospitalization or emergency-care episode", "Functional or mobility decline", "New cognitive or behavioral change", "Significant fall", "Major medication or treatment change", "New level of personal-care support"] },
    { heading: "Focused, but still person-centered", paragraphs: ["The RN evaluates the reported change within the resident’s broader clinical context and documents how current support or safety needs may be affected."] },
    { heading: "Care planning may also need review", paragraphs: ["When assessed needs change, the individualized or negotiated care plan may need to be updated so daily guidance remains current."] },
  ], relatedService: "change-in-condition-assessment" },
] as const;
export function resourcePath(resource: ResourceDefinition) { return `/resources/${resource.slug}`; }
